### ISSUE TITLE
 invalid username or password for user "default"

### ISSUE THREAD

**Issue by shashankkoppar** [Vertamedia/chproxy#100]
Hello, I am trying to use chproxy for our four node clickhouse cluster! and following in my config and error which i am getting! 

I installed chproxy by running the command as specified 

```
go get -u github.com/Vertamedia/chproxy
```

config.yml
```
$cat config.yml  
server:
  http:
    listen_addr: :9090
    allowed_networks:
    - 127.0.0.1/32
    forceautocerthandler: false
    read_timeout: 1m
    write_timeout: 2m
    idle_timeout: 10m
clusters:
- name: admin
  scheme: http
  nodes:
  - ip1:8123
  - ip2:8123
  - ip3:8123
  - ip4:8123
  users:
  - name: admin
    password: myadmin_pass
  heartbeat:
    interval: 5s
    timeout: 3s
    request: /?query=SELECT%201
    response: |
      1
users:
- name: admin
  password: myadmin_pass
  to_cluster: admin
  to_user: admin
  max_concurrent_queries: 6
  max_execution_time: 1m
log_debug: true
```

When I run this! I am getting following error! 

```
 ./chproxy -config config.yml                                                                            
INFO: 2020/11/09 17:39:08 main.go:44: chproxy ver. unknown, rev. unknown, built at unknown
INFO: 2020/11/09 17:39:08 main.go:45: Loading config: config.yml
INFO: 2020/11/09 17:39:08 main.go:272: Loaded config:
server:
  http:
    listen_addr: :9090
    allowed_networks:
    - 127.0.0.1/32
    forceautocerthandler: false
    read_timeout: 1m
    write_timeout: 2m
    idle_timeout: 10m
clusters:
- name: admin
  scheme: http
  nodes:
  - ip1:8123
  - ip2:8123
  - ip3:8123
  - ip4:8123
  users:
  - name: admin
    password: XXX
  heartbeat:
    interval: 5s
    timeout: 3s
    request: /?query=SELECT%201
    response: |
      1
users:
- name: admin
  password: XXX
  to_cluster: admin
  to_user: admin
  max_concurrent_queries: 6
  max_execution_time: 1m
log_debug: true
INFO: 2020/11/09 17:39:08 main.go:53: Loading config "config.yml": successful
INFO: 2020/11/09 17:39:08 main.go:152: Serving http on ":9090"
ERROR: 2020/11/09 17:39:14 proxy.go:59: "127.0.0.1:62293": invalid username or password for user "default"; query: ""
```

Please let me know how can I fix this issue!

**Comment by shashankkoppar** [comment]
I does work if pass user and password directly but i don't wanna do it again since i am already passing it in config! 

```
curl -X GET  "http://localhost:9090/?user=admin&password=myadminpass"
Code: 62, e.displayText() = DB::Exception: Empty query (version 20.9.2.20 (official build)) 
```

Please let me know what i am missing in configuration?

**Comment by shashankkoppar** [comment]
@hagen1778, would appreciate if u help me out here.

**Comment by hagen1778** [comment]
Hi @shashankkoppar!
Chproxy config maps users from `.users` section to users in `.clusters.users` section. So current config will work in the following way: if your query contains creds for user `admin` - it will be routed to cluster `admin` and query to CH will be send with creds from `clusters['admin'].users['admin']`.
If no creds passed with query - `default` username will be used. Pls see more here https://github.com/Vertamedia/chproxy#users
I guess, you need to make the following change to make it work:
```
users:
- name: default
  to_cluster: admin
```
However, I don't think this way ˆ is secure :-)

**Comment by zhanghaicheng1** [comment]
> I does work if pass user and password directly but i don't wanna do it again since i am already passing it in config!
> 
> ```
> curl -X GET  "http://localhost:9090/?user=admin&password=myadminpass"
> Code: 62, e.displayText() = DB::Exception: Empty query (version 20.9.2.20 (official build)) 
> ```
> 
> Please let me know what i am missing in configuration?

I also encountered this problem, if it is resolved, please contact me, thank you！

**Comment by shashankkoppar** [comment]
Thanks @hagen1778 , will try it out. I know it is insecure but i am planning to use it like sidecar proxy in kubernetes container so it is not exposed anywhere

**Comment by shashankkoppar** [comment]
```
server:
  http:
    listen_addr: :9090
    allowed_networks:
    - 127.0.0.1/32
    forceautocerthandler: false
    read_timeout: 1m
    write_timeout: 2m
    idle_timeout: 10m
clusters:
- name: admin
  scheme: http
  nodes:
  - ip1:8123
  - ip2:8123
  - ip3:8123
  - ip4:8123
  users:
  - name: admin
    password: myadmin_pass
  heartbeat:
    interval: 5s
    timeout: 3s
    request: /?query=SELECT%201
    response: |
      1
users:
- name: default
  to_cluster: admin
  to_user: admin
  max_concurrent_queries: 6
  max_execution_time: 1m
log_debug: true
```
thanks it works with this 
@zhanghaicheng1 check above conf here, this should work
