### ISSUE TITLE
[Feature Request] Store cache in RAM

### ISSUE THREAD

**Issue by iShift** [Vertamedia/chproxy#13]
It would be good if i can save cache to RAM (and perfect if i can set expire time for RAM and HDD separately)

**Comment by hagen1778** [comment]
Hi @iShift 
I suppose there no big difference between in-memory storage and HDD because of  [Linux page cache](https://www.thomas-krenn.com/en/wiki/Linux_Page_Cache_Basics)
So you can count on much faster responses for repeated reads of the same files just like as they were read from in-memory storage.

**Comment by valyala** [comment]
Closing this issue, since, as @hagen1778 said, in-memory cache would only complicate the code without performance improvements because of [page cache](https://www.thomas-krenn.com/en/wiki/Linux_Page_Cache_Basics).

**Comment by valyala** [comment]
> and perfect if i can set expire time for RAM and HDD separately

Just create two caches with distinct expiration times and assign then to different users:

```yml
caches:
  - name: "short-term"
    dir: "/path/to/cache/dir/shrot-term"
    max_size: 150Mb
    expire: 120s

  - name: "long-term"
    dir: "/path/to/cache/dir/long-term"
    max_size: 100Gb
    expire: 1000h
```
