### ISSUE TITLE
Provide docker images

### ISSUE THREAD

**Issue by tacyuuhon** [Vertamedia/chproxy#19]
Hi,guys

I run chproxy with Docker in the production env.
It brings me too much convenience. I like Docker
Can you provide a Docker images? I think this is a good idea.

Of course, I also created the docker image of chproxy.
If you think it's good, you can use it directly.
[Dockerfile](https://github.com/tacyuuhon/clickhouse-chproxy)
[Docker Hub](https://hub.docker.com/r/tacyuuhon/clickhouse-chproxy/)

Merry Christmas :christmas_tree::christmas_tree::christmas_tree::tada::tada:

**Comment by hagen1778** [comment]
Hi @tacyuuhon 
Frankly I don't see much sense in docker image - `chproxy` consists of binary and config file, which is pretty simple to handle or deploy. But if you deem it as "must have" option then we could add references to your repository.

**Comment by tacyuuhon** [comment]
Hi @hagen1778 
I think it is necessary to explain how I manage and deploy service in a cluster.
Maybe this is the missing part of the issue.

I define 4 services in the cluster:
* [Tabix](https://tabix.io/)
* [Grafana](https://grafana.com/)
* [Chproxy](https://github.com/Vertamedia/chproxy)
* [ClickHouse](https://clickhouse.yandex/)

I need to write a `docker-compose.yml` to manage them more easily.
> docker-compose.yml
```
version: '3'
services:
    tabix-ui:
      image: spoonest/clickhouse-tabix-web-client:stable
      restart: always
      network_mode: host
      ports:
        - 8080:80
        
    grafana:
      image: grafana/grafana:4.6.3
      restart: always
      network_mode: host
      ports:
        - 8081:3000
      environment:
        GF_INSTALL_PLUGINS: "vertamedia-clickhouse-datasource"
        
    chproxy:
      image: tacyuuhon/clickhouse-chproxy:1.9.0
      restart: always
      network_mode: host
      ports:
        - 9090:9090
      volumes:
        - ./conf/chproxy/config.yml:/opt/config.yml

    clickhouse-server: 
      image: yandex/clickhouse-server:1.1.54327
      restart: always
      ulimits:
        nofile:
          soft: 262144
          hard: 262144
      network_mode: host
      ports:
        - 9000:9000
        - 8123:8123
        - 9009:9009
      volumes:
        - ./data/clickhouse:/var/lib/clickhouse
        - ./conf/clickhouse/config.xml:/etc/clickhouse-server/config.xml
        - ./conf/clickhouse/users.xml:/etc/clickhouse-server/users.xml
```

If deploy them in a cluster, just need to execute the docker command.
```
docker-compose up -d
```

If upgrade the service to a new version or rollback to old version,Just modify the `docker-compose.yml` and reexecute the `docker-compose up -d` command.
e.g. (upgrade chproxy to new version)
```
    chproxy:
      image: tacyuuhon/clickhouse-chproxy:1.10.0
      ...
```
If necessary, the Docker command can be used to complete the scaling of the service
```
docker-compose scale chproxy=2
```

As you can see, this is just my use case.
Docker saves me more time, and it's easier to manage.

If you think my use case helps you and plans to publish the Docker version of chproxy, i hope you can manage it.This may be correct. 
More accurately, maybe I just provided a sample in [Dockerfile](https://github.com/tacyuuhon/clickhouse-chproxy)
