### ISSUE TITLE
Unknown setting no_cache

### ISSUE THREAD

**Issue by AntonKuzValid** [Vertamedia/chproxy#43]
I have several clients written over jdbc using ch-proxy. i Have standard configuration - 
```
log_debug: true

hack_me_please: true
server:
  http:
    listen_addr: ":9090"

users:
  - name: "..."


clusters:
  - name: ".."

     Requests are spread in `round-robin` + `least-loaded` fashion among nodes.
     Unreachable and unhealthy nodes are skipped.
    nodes: [
....
    ]
```

And when i'm trying to send a request with external data (using post method i suppose) ch-proxy adds paramter no_cache and click house throw an exception - Code: 115, e.displayText() = DB::Exception: Unknown setting no_cache.

I suppose it woud be nice to remove this 

```
// disable cache for external_data queries
			params.Set("no_cache", "1")
			log.Debugf("external data params detected - cache will be disabled")
```
