### ISSUE TITLE
pass format_schema query param setting to clickhouse

### ISSUE THREAD

**Issue by kcking** [Vertamedia/chproxy#63]
We are setting `format_schema` as a query parameter in our POST request, however when chproxy proxies the request, this parameter is not included and Clickhouse errors with `DB::Exception: The format Protobuf requires a schema. The 'format_schema' setting should be set (version 19.14.6.12 (official build))`

This would be resolved if chproxy forwarded this query parameter to the server.

**Comment by hagen1778** [comment]
Hi @kcking !
Pls see similar issue https://github.com/Vertamedia/chproxy/issues/62

**Comment by theRealWardo** [comment]
#62 helped solve a similar problem I had. thanks @hagen1778 

a snippet of something like an example config for future visitors:

```
...
users:
  - name: "mux"
    password: "asdf1234"
    to_cluster: "clickhouse"
    to_user: "default"
    params: "protoplz"
param_groups:
  - name: "protoplz"
    params:
      - key: "format_schema"
        value: "the_proto_file:MessageName"
...
```
